import { mkdir, writeFile, rm, copyFile } from 'node:fs/promises';
import { person as p, experience, projects, capabilities, education, research } from '../data/portfolio.mjs';
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow = '<span aria-hidden="true">↗</span>';
const tags = a => `<div class="tags">${a.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`;
const configuredUrl = process.env.SITE_URL || p.siteUrl;
const base = configuredUrl ? configuredUrl.replace(/\/$/, '') + '/' : '';
if (base && !/^https:\/\/[^/]+\//.test(base)) throw new Error('siteUrl must be an HTTPS URL');
const head = (title, description, path = '', prefix = '') => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f7f8f5">
<meta property="og:type" content="website"><meta property="og:locale" content="en_US"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${esc(base || prefix)}assets/social-preview.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Sanjoy Kumar Sarkar — IT & Digital Systems Professional">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(base || prefix)}assets/social-preview.png">
${base ? `<link rel="canonical" href="${esc(base + path)}"><meta property="og:url" content="${esc(base + path)}">` : ''}
<link rel="icon" type="image/svg+xml" href="${prefix}assets/favicon.svg"><link rel="stylesheet" href="${prefix}styles.css"><script src="${prefix}script.js" defer></script></head>`;
const brand = (prefix='') => `<a class="brand" href="${prefix || '#home'}"><span class="brand-mark" aria-hidden="true">s<span>.</span></span><span>Sanjoy Sarkar<span class="brand-sub">IT & DIGITAL SYSTEMS</span></span></a>`;
const nav = (sub=false) => `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container nav-inner">${brand(sub?'../index.html':'')} ${sub?'<a class="text-link" href="../index.html#projects">← All selected work</a>':`<button class="menu-btn" type="button" aria-expanded="false" aria-controls="navigation" aria-label="Open navigation"><span></span><span></span></button><nav id="navigation" class="nav-links" aria-label="Main navigation"><a href="#about">About</a><a href="#projects">Work</a><a href="#experience">Experience</a><a href="#skills">Capabilities</a><a href="#research">Research</a><a class="nav-cta" href="#contact">Let’s connect ${arrow}</a></nav>`}</div></header>`;
const footer = (prefix='') => `<footer><div class="container footer-inner"><span>© <span id="year">2026</span> Sanjoy Kumar Sarkar</span><span>Based in Bangladesh. Open to the world.</span><a href="${prefix || '#home'}">Back to ${prefix?'home':'top'} ↑</a></div></footer>`;
const heading = (n, label, title, text='') => `<div class="section-heading"><div><div class="eyebrow">${n} / ${label}</div><h2>${title}</h2></div>${text?`<p>${text}</p>`:''}</div>`;
const projectCard = (x,i) => `<article class="project-card ${i===0?'featured':''}"><div class="project-visual visual-${i}" aria-hidden="true">${i===0?`<div class="diagram-label"><span class="live-dot"></span> CLIMATE-INFORMED SURVEILLANCE</div><div class="system-diagram"><div class="source-pair"><span>Climate data</span><span>Disease surveillance</span></div><div class="connector"></div><div class="database-node"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3"><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0"/></svg><span>Connected data systems<small>PostgreSQL · Python · APIs</small></span></div><div class="connector"></div><div class="output-node">Early warning & decision support <span>↗</span></div></div><span class="visual-caption">Conceptual workflow illustration</span>`:i===1?'<div class="mini-pipeline"><span>{ API }</span><i>→</i><span class="pipeline-db">SQL</span><i>→</i><span>Insights ↗</span></div><span class="visual-caption">Collect. Validate. Connect.</span>':i===2?'<div class="mis-illustration"><span>Programme needs</span><span>Information systems</span><span>Reporting & adoption ↗</span></div>':'<div class="network-illustration"><span>HQ</span><i>―</i><strong>IT operations</strong><i>―</i><span>Field</span></div><span class="visual-caption">Infrastructure that supports people</span>'}</div><div class="project-body"><div class="project-label"><span>${esc(x.category)}</span><span>${x.number}</span></div><h3><a href="projects/${x.slug}.html">${esc(x.title)}</a></h3><p>${esc(x.summary)}</p>${tags(x.tags)}<a class="text-link" href="projects/${x.slug}.html">Explore case study <span aria-hidden="true">→</span><span class="sr-only">: ${esc(x.fullTitle)}</span></a></div></article>`;
await mkdir('projects',{recursive:true});
await mkdir('assets',{recursive:true});
await writeFile('index.html',`${head(`${p.name} | ${p.title}`,p.description)}<body>${nav()}<main id="main">
<section class="hero" id="home"><div class="container hero-grid"><div class="hero-copy"><div class="availability"><span class="live-dot"></span> OPEN TO OPPORTUNITIES</div><p class="hero-name">Hello, I’m Sanjoy Kumar Sarkar.</p><h1>Reliable technology.<br><span>Real-world impact.</span></h1><p class="hero-role">IT & Digital Systems Professional</p><p class="hero-description">Around eight years connecting infrastructure, people and information systems across international development and public health.</p><div class="hero-actions"><a class="button primary" href="#projects">Explore my work ${arrow}</a><a class="button secondary" href="assets/Sanjoy_Sarkar_CV.pdf" download>Download CV <span aria-hidden="true">↓</span></a></div><div class="hero-location"><span aria-hidden="true">◎</span> Bangladesh <span class="divider">/</span> International perspective</div></div><aside class="profile-panel" aria-label="Professional snapshot"><div class="profile-person"><img src="assets/sanjoy-sarkar.jpg" alt="Sanjoy Sarkar" width="72" height="72" fetchpriority="high"><div><strong>Sanjoy Sarkar</strong><span>Infrastructure to digital health</span></div><span class="profile-symbol" aria-hidden="true">↗</span></div><div class="panel-title">A career built on<br><em>making systems work.</em></div><div class="profile-stats"><div><strong>~8<span>years</span></strong><p>Progressive IT experience</p></div><div><strong>4<span>organizations</span></strong><p>Development & public health</p></div></div><div class="expertise-rows"><div><span>01</span> Infrastructure & IT operations <span>↗</span></div><div><span>02</span> MIS & enterprise platforms <span>↗</span></div><div><span>03</span> Digital health & data systems <span>↗</span></div></div><a href="#experience" class="profile-bottom">Explore my experience <span aria-hidden="true">→</span></a></aside></div></section>
<section class="organizations" aria-label="Organizations I have worked with"><div class="container"><p>ORGANIZATIONS I HAVE WORKED WITH</p><div class="org-list"><span>Save the Children</span><span>Oxfam<span class="org-detail">BANGLADESH</span></span><span>Winrock<span class="org-detail">INTERNATIONAL</span></span><span>IEDCR<span class="org-detail">PUBLIC HEALTH · BANGLADESH</span></span></div></div></section>
<section class="section" id="about"><div class="container">${heading('01','The bigger picture','Infrastructure roots.<br>Digital systems perspective.')}<div class="about-grid"><div class="about-statement"><p>I help organizations implement, operate and improve <span>technology that people depend on.</span></p><a href="#contact" class="text-link">Let’s talk about your team ${arrow}</a></div><div class="about-copy"><p>My career began in enterprise ICT infrastructure and user support at Save the Children. It expanded into independent field IT operations at Oxfam, MIS and digital transformation at Winrock International, and public-health data systems at IEDCR.</p><p>That progression lets me work across Microsoft 365, networks and endpoints as well as PostgreSQL, Linux, Python-backed services and dashboards. I bring a practical understanding of the users, systems and operational constraints behind each technical decision.</p></div></div><ol class="career-path" aria-label="Career progression">${[...experience].reverse().map(x=>`<li><span class="path-year">${x.year}</span><strong>${esc(x.focus)}</strong><span>${esc(x.org.replace(' Bangladesh',''))}</span></li>`).join('')}</ol></div></section>
<section class="section tinted" id="projects"><div class="container">${heading('02','Selected work','Practical systems.<br>Meaningful responsibilities.','Four professional case studies across public health, programme information and enterprise IT. Explore the context, my contribution and the work behind the tools.')}<div class="project-grid">${projects.map(projectCard).join('')}</div></div></section>
<section class="section" id="experience"><div class="container">${heading('03','Professional experience','A wider remit.<br>With every chapter.','From supporting enterprise infrastructure to contributing to national public-health systems, each role added technical depth and operational responsibility.')}<div class="experience-list">${experience.map((x,i)=>`<article class="experience-row"><div class="experience-date"><span class="timeline-dot" aria-hidden="true"></span><span>${x.dates}</span><small>0${4-i} / ${esc(x.focus)}</small></div><div class="experience-content"><div class="experience-title"><h3>${esc(x.org)}</h3><a href="projects/${x.project}.html" aria-label="View related case study for ${esc(x.org)}">${arrow}</a></div><p class="job-role">${esc(x.role)}</p>${x.fullName?`<p class="org-full">${esc(x.fullName)}</p>`:''}<p>${esc(x.summary)}</p><ul>${x.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul>${tags(x.tags)}</div></article>`).join('')}</div></div></section>
<section class="section capabilities-section" id="skills"><div class="container">${heading('04','Core capabilities','Technical depth.<br>Operational understanding.','Established strengths in infrastructure and support, complemented by hands-on data systems work and growing backend capability.')}<div class="capability-grid">${capabilities.map((x,i)=>`<article class="capability"><span class="capability-number">0${i+1}</span><span class="level">${x.level}</span><h3>${x.title}</h3><p>${x.text}</p><div class="capability-tools">${x.tools}</div></article>`).join('')}</div><div class="developing"><span>CONTINUING TO DEVELOP</span><p>Cloud engineering · Advanced PostgreSQL performance tuning · DevOps practices · AI & data engineering</p></div></div></section>
<section class="section"><div class="container">${heading('05','How I work','Good technology starts<br>with understanding the work.')}<ol class="approach">${[['Understand','Listen to users and define the operational need.'],['Assess','Map the systems, data, risks and constraints.'],['Implement','Choose practical, maintainable solutions.'],['Enable','Help people use the system with confidence.'],['Improve','Monitor, document and troubleshoot.']].map(([a,b])=>`<li><h3>${a}</h3><p>${b}</p></li>`).join('')}</ol></div></section>
<section class="section tinted" id="research"><div class="container">${heading('06','Research & conference contributions','Connecting practice<br>with emerging ideas.','Contributions at the intersection of climate, disease surveillance and early warning.')}<div class="research-list">${research.map(r=>`<article class="research-row"><span class="research-year">${r.year}</span><div><span class="research-status">${esc(r.status)}</span><h3>${esc(r.title)}</h3><p class="authors">${esc(r.authors)}</p><p>${esc(r.venue)}</p><p class="research-note">${esc(r.note)}</p></div></article>`).join('')}</div><div class="interests"><h3>Areas I am exploring</h3><p>Climate-informed early warning · Health forecasting · Applied machine learning · Probabilistic forecasting · AI for public-sector systems · Data engineering · Reliable digital public infrastructure</p></div></div></section>
<section class="section" id="education"><div class="container">${heading('07','Education & continued learning','Experience, with a<br>commitment to keep growing.')}<div class="education-grid">${education.map(e=>`<article class="education-card"><span class="education-period">${esc(e.period)}</span><h3>${esc(e.degree)}</h3><p class="institution">${esc(e.institution)}</p><p>${esc(e.description)}</p></article>`).join('')}</div></div></section>
<section class="contact-section" id="contact"><div class="container contact-grid"><div><div class="eyebrow">08 / Let’s work together</div><h2>Technology that works.<br><span>A team to build it with.</span></h2><p>I’m open to opportunities in IT operations, infrastructure, digital systems, MIS and digital health—in Bangladesh and internationally.</p><a class="button primary" href="mailto:${p.email}">Get in touch ${arrow}</a></div><div class="contact-details"><span>HAVE AN OPPORTUNITY IN MIND?</span><a class="email-link" href="mailto:${p.email}">${p.email} ${arrow}</a><div class="social-links"><a href="${p.linkedin}" target="_blank" rel="noopener noreferrer">LinkedIn ${arrow}</a><a href="${p.github}" target="_blank" rel="noopener noreferrer">GitHub ${arrow}</a><a href="assets/Sanjoy_Sarkar_CV.pdf" download>Download CV ↓</a></div><p>Based in Bangladesh<br>Available for professional opportunities & collaboration.</p></div></div></section>
</main>${footer()}${base?`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Person',name:p.name,jobTitle:p.title,url:base,sameAs:[p.linkedin,p.github]}).replace(/</g,'\\u003c')}</script>`:''}</body></html>`);
for(const x of projects){
 const next=projects[(projects.indexOf(x)+1)%projects.length];
 await writeFile(`projects/${x.slug}.html`,`${head(`${x.fullTitle} | ${p.shortName}`,x.summary,`projects/${x.slug}.html`,'../')}<body>${nav(true)}<main id="main"><header class="case-hero"><div class="container"><div class="eyebrow">CASE STUDY ${x.number} / ${esc(x.category)}</div><h1>${esc(x.fullTitle)}</h1><p>${esc(x.summary)}</p>${tags(x.tags)}</div></header><div class="container"><div class="case-facts"><div><span>CONTEXT</span><strong>${esc(x.context)}</strong></div><div><span>PERIOD</span><strong>${x.period}</strong></div><div><span>CONTRIBUTION</span><strong>Technical implementation & operational support</strong></div></div><figure class="case-flow"><figcaption>How the work connects <span>Conceptual illustration · Not an internal architecture or product screenshot</span></figcaption><ol class="flow" aria-label="Conceptual workflow">${x.flow.map((s,i)=>`<li><span class="flow-number">0${i+1}</span><span>${esc(s)}</span></li>`).join('')}</ol></figure><div class="case-layout"><nav class="case-toc" aria-label="Case study contents"><span>IN THIS CASE STUDY</span>${['The challenge','My role','The approach','The result','Lessons'].map((t,i)=>`<a href="#part-${i}">${t}</a>`).join('')}<a href="../assets/Sanjoy_Sarkar_CV.pdf" download>Download CV ↓</a></nav><div class="case-content"><section id="part-0"><div class="eyebrow">01 / Context</div><h2>The challenge</h2><p>${esc(x.challenge)}</p></section><section id="part-1"><div class="eyebrow">02 / Contribution</div><h2>My role</h2><p>${esc(x.role)}</p></section><section id="part-2"><div class="eyebrow">03 / Delivery</div><h2>The approach</h2><ul>${x.approach.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><h3 class="technology-title">Technology & working environment</h3>${tags(x.technology)}</section><section id="part-3"><div class="eyebrow">04 / Operational value</div><h2>The result</h2><p>${esc(x.result)}</p></section><section id="part-4"><div class="eyebrow">05 / Reflection</div><h2>What this work reinforced</h2><p>${esc(x.lesson)}</p></section><aside class="confidentiality">This case study describes my contribution at a high level. No internal infrastructure details, sensitive datasets or private dashboards are shared.</aside><div class="next-project"><span>NEXT CASE STUDY</span><a href="${next.slug}.html">${esc(next.fullTitle)} ${arrow}</a></div></div></div></div></main>${footer('../index.html')}</body></html>`);
}
await writeFile('404.html',`${head('Page not found | Sanjoy Sarkar','This page could not be found.','404.html',base)}<body><main class="not-found" id="main"><div class="eyebrow">404 / Page not found</div><h1>Let’s get you<br>back on track.</h1><p>The page may have moved, or the link may be incomplete.</p><a class="button primary" href="${base||'./index.html'}">Back to portfolio →</a></main></body></html>`);
await writeFile('robots.txt',`User-agent: *\nAllow: /\n${base?`Sitemap: ${base}sitemap.xml\n`:''}`);
if(base) await writeFile('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['',...projects.map(x=>`projects/${x.slug}.html`)].map(path=>`<url><loc>${esc(base+path)}</loc></url>`).join('')}</urlset>`);
else await rm('sitemap.xml',{force:true});
// Publish only the explicit public output, never the private original CV or sources.
await mkdir('dist/assets',{recursive:true});
await mkdir('dist/projects',{recursive:true});
for(const file of ['index.html','404.html','styles.css','script.js','robots.txt','.nojekyll']) await copyFile(file,`dist/${file}`);
for(const x of projects) await copyFile(`projects/${x.slug}.html`,`dist/projects/${x.slug}.html`);
for(const file of ['favicon.svg','sanjoy-sarkar.jpg','Sanjoy_Sarkar_CV.pdf','social-preview.png']) await copyFile(`assets/${file}`,`dist/assets/${file}`);
if(base) await copyFile('sitemap.xml','dist/sitemap.xml');
else await rm('dist/sitemap.xml',{force:true});
console.log(`Built homepage and ${projects.length} case studies. ${base?'SEO URLs configured.':'Set person.siteUrl before publishing to generate canonical URLs and sitemap.'}`);
