import { mkdir, writeFile, rm, copyFile, readFile } from 'node:fs/promises';
import { renderHomepage } from './homepage.mjs';
import { createHash } from 'node:crypto';
import { person as p, experience, projects, capabilities, education, research } from '../data/portfolio.mjs';
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const whatsappUrl = p.whatsapp ? `https://wa.me/${p.whatsapp.replace(/\D/g, '')}` : '';
const arrow = '<span aria-hidden="true">↗</span>';
const tags = a => `<div class="tags">${a.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`;
const assetVersion = async file => createHash('sha256').update(await readFile(file)).digest('hex').slice(0,12);
const cssVersion = await assetVersion('styles.css');
const jsVersion = await assetVersion('script.js');
const configuredUrl = process.env.SITE_URL || p.siteUrl;
const base = configuredUrl ? configuredUrl.replace(/\/$/, '') + '/' : '';
if (base && !/^https:\/\/[^/]+\//.test(base)) throw new Error('siteUrl must be an HTTPS URL');
const head = (title, description, path = '', prefix = '') => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#faf9f6">
<meta property="og:type" content="website"><meta property="og:locale" content="en_US"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${esc(base || prefix)}assets/social-preview.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Sanjoy Kumar Sarkar — IT & Digital Systems Professional">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(base || prefix)}assets/social-preview.png">
${base ? `<link rel="canonical" href="${esc(base + path)}"><meta property="og:url" content="${esc(base + path)}">` : ''}
<link rel="icon" type="image/svg+xml" href="${prefix}assets/favicon.svg"><link rel="stylesheet" href="${prefix}styles.css?v=${cssVersion}"><script src="${prefix}script.js?v=${jsVersion}" defer></script></head>`;
const brand = (prefix='') => `<a class="brand" href="${prefix || '#home'}"><span class="brand-mark" aria-hidden="true">s.</span><span>Sanjoy Sarkar</span></a>`;
const nav = (sub=false) => `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container nav-inner">${brand(sub?'../index.html':'')} ${sub?'<a class="text-link" href="../index.html#projects">← All selected work</a>':`<button class="menu-btn" type="button" aria-expanded="false" aria-controls="navigation" aria-label="Open navigation"><span></span><span></span></button><nav id="navigation" class="nav-links" aria-label="Main navigation"><a href="#about">My story</a><a href="#projects">Work</a><a href="#experience">Journey</a><a href="#skills">Skills</a><a href="#research">Research</a><a class="nav-cta" href="#contact">Let’s connect ${arrow}</a></nav>`}</div></header>`;
const footer = (prefix='') => `<footer><div class="container footer-inner"><span>© <span id="year">2026</span> Sanjoy Kumar Sarkar</span><span>Based in Bangladesh. Open to the world.</span><a href="${prefix || '#home'}">Back to ${prefix?'home':'top'} ↑</a></div></footer>`;
const heading = (n, label, title, text='') => `<div class="section-heading"><div><div class="eyebrow">${n} / ${label}</div><h2>${title}</h2></div>${text?`<p>${text}</p>`:''}</div>`;
const projectDetails = x => !x.details?.length ? '' : `<section id="work-details" class="work-details"><div class="eyebrow">Hands-on responsibilities</div><h2>${esc(x.detailTitle)}</h2><p>${esc(x.detailIntro)}</p><div class="evidence-grid">${x.details.map(d=>`<article class="evidence-card"><h3>${esc(d.title)}</h3><p>${esc(d.text)}</p><ul>${d.items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></article>`).join('')}</div></section>`;
await mkdir('projects',{recursive:true});
await mkdir('assets',{recursive:true});
const dialog = `<dialog class="contact-dialog" id="contact-dialog" aria-labelledby="contact-dialog-title" aria-describedby="contact-dialog-description"><div class="dialog-inner"><button class="dialog-close" type="button" aria-label="Close contact window" autofocus>×</button><div class="eyebrow">Let’s start a conversation</div><h2 id="contact-dialog-title">Get in touch.</h2><p id="contact-dialog-description">Have a role or collaboration in mind? Choose how you’d like to get in touch.</p><div class="dialog-email"><span id="contact-email">${p.email}</span><button type="button" class="copy-email" data-email="${p.email}">Copy email</button></div><div class="dialog-options"><a class="button primary" href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;to=${encodeURIComponent(p.email)}&amp;su=Professional%20opportunity" target="_blank" rel="noopener noreferrer">Open Gmail ↗</a><a class="button secondary" href="mailto:${p.email}?subject=Professional%20opportunity">Open email app ↗</a></div><p class="dialog-hint">Gmail opens in a new tab. Prefer another service? Copy my address and use your usual inbox.</p><p class="copy-status" role="status" aria-live="polite"></p>${whatsappUrl ? `<section class="dialog-whatsapp" aria-labelledby="whatsapp-title"><div><h3 id="whatsapp-title">Prefer WhatsApp?</h3><p>Start a conversation with me directly.</p></div><a class="button whatsapp-button" href="${whatsappUrl}" target="_blank" rel="noopener noreferrer">Chat on WhatsApp ${arrow}</a></section>` : ''}<a class="text-link" href="${p.linkedin}" target="_blank" rel="noopener noreferrer">Or connect on LinkedIn ↗</a></div></dialog>`;
await writeFile('index.html',renderHomepage({head,nav,footer,dialog}));
for(const x of projects){
 const next=projects[(projects.indexOf(x)+1)%projects.length];
 await writeFile(`projects/${x.slug}.html`,`${head(`${x.fullTitle} | ${p.shortName}`,x.summary,`projects/${x.slug}.html`,'../')}<body>${nav(true)}<main id="main"><header class="case-hero"><div class="container"><div class="eyebrow">CASE STUDY ${x.number} / ${esc(x.category)}</div><h1>${esc(x.fullTitle)}</h1><p>${esc(x.summary)}</p>${tags(x.tags)}</div></header><div class="container"><div class="case-facts"><div><span>CONTEXT</span><strong>${esc(x.context)}</strong></div><div><span>PERIOD</span><strong>${x.period}</strong></div><div><span>CONTRIBUTION</span><strong>${esc(x.contribution || 'Technical implementation & operational support')}</strong></div></div><figure class="case-flow"><figcaption>How the work connects <span>Conceptual illustration · Not an internal architecture or product screenshot</span></figcaption><ol class="flow" aria-label="Conceptual workflow">${x.flow.map((s,i)=>`<li><span class="flow-number">0${i+1}</span><span>${esc(s)}</span></li>`).join('')}</ol></figure><div class="case-layout"><nav class="case-toc" aria-label="Case study contents"><span>IN THIS CASE STUDY</span>${['The challenge','My role','The approach'].map((t,i)=>`<a href="#part-${i}">${t}</a>`).join('')}${x.details?.length ? `<a href="#work-details">${esc(x.detailTitle)}</a>` : ''}<a href="#part-3">The result</a><a href="#part-4">Lessons</a><a href="../assets/Sanjoy_Sarkar_CV.pdf" download>Download CV ↓</a></nav><div class="case-content"><section id="part-0"><div class="eyebrow">01 / Context</div><h2>The challenge</h2><p>${esc(x.challenge)}</p></section><section id="part-1"><div class="eyebrow">02 / Contribution</div><h2>My role</h2><p>${esc(x.role)}</p></section><section id="part-2"><div class="eyebrow">03 / Delivery</div><h2>The approach</h2><ul>${x.approach.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><h3 class="technology-title">Technology & working environment</h3>${tags(x.technology)}</section>${projectDetails(x)}<section id="part-3"><div class="eyebrow">04 / Operational value</div><h2>The result</h2><p>${esc(x.result)}</p></section><section id="part-4"><div class="eyebrow">05 / Reflection</div><h2>What this work reinforced</h2><p>${esc(x.lesson)}</p></section><aside class="confidentiality">This case study describes my contribution at a high level. No internal infrastructure details, sensitive datasets or private dashboards are shared.</aside><div class="next-project"><span>NEXT CASE STUDY</span><a href="${next.slug}.html">${esc(next.fullTitle)} ${arrow}</a></div></div></div></div></main>${footer('../index.html')}</body></html>`);
}
await writeFile('404.html',`${head('Page not found | Sanjoy Sarkar','This page could not be found.','404.html',base)}<body><main class="not-found" id="main"><div class="eyebrow">404 / Page not found</div><h1>Let’s get you<br>back on track.</h1><p>The page may have moved, or the link may be incomplete.</p><a class="button primary" href="${base||'./index.html'}">Back to portfolio →</a></main></body></html>`);
await writeFile('robots.txt',`User-agent: *\nAllow: /\n${base?`Sitemap: ${base}sitemap.xml\n`:''}`);
if(base) await writeFile('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['',...projects.map(x=>`projects/${x.slug}.html`)].map(path=>`<url><loc>${esc(base+path)}</loc></url>`).join('')}</urlset>`);
else await rm('sitemap.xml',{force:true});
// Publish only the explicit public output, never the private original CV or sources.
await mkdir('dist/assets',{recursive:true});
await mkdir('dist/projects',{recursive:true});
for(const file of ['index.html','404.html','styles.css','script.js','robots.txt','.nojekyll']) await copyFile(file,`dist/${file}`);
for(const x of projects) await copyFile(`projects/${x.slug}.html`,`dist/projects/${x.slug}.html`);
for(const file of ['skill-python.svg','skill-postgresql.svg','skill-docker.svg','skill-linux.svg','skill-fastapi.svg','skill-git.svg','skill-nginx.svg','DEVICON-LICENSE.txt','favicon.svg','sanjoy-portrait.png','sanjoy-sarkar.jpg','Sanjoy_Sarkar_CV.pdf','social-preview.png','save-the-children-logo.svg','oxfam-logo.png','winrock-logo.png','iedcr-logo.png']) await copyFile(`assets/${file}`,`dist/assets/${file}`);
if(base) await copyFile('sitemap.xml','dist/sitemap.xml');
else await rm('dist/sitemap.xml',{force:true});
console.log(`Built homepage and ${projects.length} case studies. ${base?'SEO URLs configured.':'Set person.siteUrl before publishing to generate canonical URLs and sitemap.'}`);
