import { renderJourney, renderOrigin, renderNext } from './story.mjs';
import { person as p, projects, research } from '../data/portfolio.mjs';
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svg = (body, cls='') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
export const icons = {
 home:svg('<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>'),
 work:svg('<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 12c6 4 12 4 18 0M12 12v4"/>'),
 layers:svg('<path d="m3 7 9-4 9 4-9 4Zm0 5 9 4 9-4M3 17l9 4 9-4"/>'),
 mail:svg('<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>'),
 download:svg('<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>'),
 arrow:svg('<path d="M5 12h14m-5-5 5 5-5 5"/>'),
 location:svg('<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>'),
 globe:svg('<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>'),
 book:svg('<path d="M12 5c-3-2-6-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1Zm0 0v15"/>'),
 school:svg('<path d="m2 8 10-5 10 5-10 5Zm4 2v7c3 3 9 3 12 0v-7M22 8v9"/>'),
 plus:svg('<path d="M12 5v14M5 12h14"/>'),
 linkedin:svg('<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M7 10v7m4 0v-7m0 3c0-4 6-4 6 0v4"/><path d="M7 7h.01" stroke-width="3"/>'),
 github:svg('<path d="M9 21v-4c-4 1-4-2-6-2m12 6v-4c0-1-.3-2-1-2 4-.5 6-2 6-5a5 5 0 0 0-1-3c.2-1 .2-2 0-3-2 0-3 1-3 1a13 13 0 0 0-8 0S7 4 5 4c-.2 1-.2 2 0 3a5 5 0 0 0-1 3c0 3 2 4.5 6 5-.7 0-1 1-1 2"/>'),
 database:svg('<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0"/>')
};
const tools = [
 ['Python','python','Working experience','Python-based collection, processing and backend components for disease and climate data.','data-automation'],
 ['PostgreSQL','postgresql','Hands-on','Database upserts, epi-week checks and data validation for surveillance workflows.','data-automation'],
 ['Linux','linux','Hands-on','Application operations, service checks and troubleshooting across Linux-hosted systems.','production-troubleshooting'],
 ['Docker','docker','Working experience','Operating containerized application services within the EWARS environment.','ewars'],
 ['Microsoft 365','microsoft','Hands-on','Account support, collaboration tools and day-to-day enterprise IT services.','enterprise-it'],
 ['FastAPI','fastapi','Working experience','Supporting Python backend components and REST APIs that connect data with dashboards.','ewars'],
 ['Git','git','Working experience','Version control within the digital-health application working environment.','ewars'],
 ['Nginx','nginx','Hands-on','Application routing, configuration checks and incident diagnosis.','production-troubleshooting'],
 ['Power BI','powerbi','Working experience','Dashboard and reporting work alongside broader MIS implementation and user support.','winrock-mis'],
 ['KoBoToolbox','kobo','Working experience','Digital data collection, field forms and structured reporting.','winrock-mis'],
 ['Azure AD','azuread','Working experience','Cloud identity, user accounts and access within Microsoft enterprise environments.','enterprise-it'],
 ['Cisco Meraki Dashboard','meraki','Working experience','Cloud-managed networking, connectivity monitoring and network troubleshooting.','enterprise-it'],
 ['Active Directory','ad','Working experience','Directory services, user accounts and access in Microsoft environments.','enterprise-it'],
 ['DHIS2','dhis2','Integration concepts','Health-information systems and integration concepts for surveillance and reporting.','ewars'],
 ['Jira','jira','Working experience','Issue tracking, task coordination and technical work management.','enterprise-it'],
 ['ServiceNow','servicenow','Working experience','IT service management, incident tracking and support workflows.','enterprise-it']
];
function toolIcon(key){
 const symbols = {
  kobo: ['#e55b42','<path d="M6 4v16M18 4l-9 8 9 8"/>'],
  azuread: ['#168bc0','<path d="m12 3 9 16H3Z"/><path d="m12 3-3 12 12 4"/>'],
  meraki: ['#649947','<path d="M3 17V9m4 8V5m5 12V3m5 14V5m4 12V9"/>'],
  ad: ['#3876b7','<rect x="9" y="2" width="6" height="6" rx="1"/><rect x="2" y="16" width="6" height="6" rx="1"/><rect x="16" y="16" width="6" height="6" rx="1"/><path d="M12 8v4H5v4m7-4h7v4"/>'],
  dhis2: ['#3270aa','<path d="M5 4h7a8 8 0 0 1 0 16H5Z"/><path d="M9 8h5m-5 4h7m-7 4h5"/>'],
  jira: ['#2673dc','<path d="m12 2 10 10-10 10L2 12Z"/><path d="m12 8 4 4-4 4-4-4Z"/>'],
  servicenow: ['#4d806b','<path d="M4 18a10 10 0 1 1 16 0l-4-3a5 5 0 1 0-8 0Z"/>']
 };
 if(symbols[key])return '<svg class="tool-icon" viewBox="0 0 24 24" fill="none" stroke="'+symbols[key][0]+'" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+symbols[key][1]+'</svg>';
 if(key==='microsoft')return '<svg class="tool-icon" viewBox="0 0 24 24" aria-hidden="true"><path fill="#f25022" d="M1 1h10v10H1z"/><path fill="#7fba00" d="M13 1h10v10H13z"/><path fill="#00a4ef" d="M1 13h10v10H1z"/><path fill="#ffb900" d="M13 13h10v10H13z"/></svg>';
 if(key==='powerbi')return '<svg class="tool-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="12" width="6" height="10" rx="2" fill="#e8b000"/><rect x="9" y="7" width="6" height="15" rx="2" fill="#f2c811"/><rect x="15" y="2" width="6" height="20" rx="2" fill="#ffda4b"/></svg>';
 return `<img class="tool-icon" src="assets/skill-${key}.svg" width="24" height="24" alt="" loading="lazy">`;
}
const chips = values=>`<div class="tags">${values.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`;
const projectNames=['Climate-informed early warning','Disease & climate data pipelines','Programme information systems','IT across headquarters & the field','Restoring dashboard access'];
function illustration(i){
 if(i===0)return `<div class="mini-window"><div class="window-top"><span class="window-dots">● ● ●</span><span>EARLY WARNING / SYSTEM OVERVIEW</span></div><div class="signal-grid"><div class="signal-sources"><span>Climate data</span><span>Disease surveillance</span></div><div class="signal-link">↓</div><div class="signal-core">${icons.database}<span>Connected information<small>PostgreSQL · Python · APIs</small></span></div><div class="signal-link">↓</div><div class="signal-output">Early warning &amp; decision support ${icons.arrow}</div></div></div>`;
 if(i===1)return `<div class="pipeline-art"><span class="art-eyebrow">FROM SOURCE TO SOMETHING USEFUL</span><div class="pipeline-nodes"><span>{ API }</span><i>→</i><span>${icons.database}</span><i>→</i><span>Insights</span></div><div class="pipeline-steps"><span>01 Collect</span><span>02 Validate</span><span>03 Connect</span></div></div>`;
 if(i===2)return `<div class="paper-stack"><div><span>01</span> Programme requirements</div><div><span>02</span> Information management</div><div><span>03</span> Reporting &amp; adoption ${icons.arrow}</div></div>`;
 if(i===3)return `<div class="network-art"><div>${icons.globe}<span>Headquarters</span></div><i>····</i><div class="network-center">${icons.layers}<span>IT operations</span></div><i>····</i><div>${icons.location}<span>Field teams</span></div></div>`;
 return `<div class="terminal-art"><div><span>● ● ●</span> Incident investigation</div><p><span>01</span> Local application <b>responding</b></p><p><span>02</span> Access path <b>investigated</b></p><p><span>03</span> Dashboard <b>reachable again</b></p></div>`;
}
export function renderHomepage({head,nav,footer,dialog}){
return `${head(`${p.name} | ${p.title}`,p.description)}<body class="home-page"><div class="reading-progress" aria-hidden="true"></div>${nav()}<main id="main" class="portfolio-main">
<section id="home" class="intro"><div class="intro-top"><span class="small-label">IT, DATA &amp; THE PEOPLE BEHIND THEM</span><a class="availability" href="#contact"><span></span> Open to opportunities</a></div><div class="intro-grid"><div class="intro-copy"><h1>Hi, I’m <em>Sanjoy.</em></h1><p class="intro-role">IT &amp; Digital Systems Professional</p><p class="intro-description">I started by supporting the technology people use every day. Eight years later, my work spans field IT, information systems and public-health data. This is the story of how those pieces came together.</p></div><figure class="intro-portrait"><div class="portrait-crop"><img src="assets/sanjoy-portrait.png" alt="Sanjoy Kumar Sarkar" width="624" height="831" fetchpriority="high"></div><figcaption>Sanjoy Kumar Sarkar</figcaption></figure></div><div class="intro-meta"><span>${icons.location} Bangladesh</span><span>${icons.work} 8 years of experience</span><span>${icons.globe} Open to international roles</span></div><div class="intro-actions"><a class="button primary" href="assets/Sanjoy_Sarkar_CV.pdf" download>${icons.download} Download CV</a><a class="button secondary" href="#experience">Follow my journey ${icons.arrow}</a><div class="intro-socials"><a href="${p.linkedin}" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">${icons.linkedin}</a><a href="${p.github}" target="_blank" rel="noopener noreferrer" aria-label="GitHub">${icons.github}</a><a href="mailto:${p.email}" data-contact-open aria-label="Email Sanjoy">${icons.mail}</a></div></div></section>
${renderOrigin({icons})}
${renderJourney({icons,esc})}
<section id="projects" class="section projects-section" data-story-label="The work"><span class="chapter-kicker">03 / THE WORK</span><div class="section-title"><h2>The work behind the story.</h2><span class="section-count">05 case studies</span></div><p class="section-intro">From keeping teams connected to keeping surveillance data moving. These case studies show my contribution, the approach I took and what each experience reinforced.</p><div class="project-filters" role="group" aria-label="Filter selected work" hidden><button type="button" data-filter="all" aria-pressed="true">All work <span>5</span></button><button type="button" data-filter="health" aria-pressed="false">Health &amp; data</button><button type="button" data-filter="operations" aria-pressed="false">IT operations</button><button type="button" data-filter="mis" aria-pressed="false">MIS</button></div><p id="filter-status" class="sr-only" role="status" aria-live="polite"></p><div class="project-grid">${[3,2,0,1,4].map(i=>{const x=projects[i];return`<article class="project-card" data-category="${i<2?'health':i===2?'mis':'operations'}"><a class="project-art art-${i}" href="projects/${x.slug}.html" tabindex="-1" aria-hidden="true">${illustration(i)}<span class="art-caption">Conceptual illustration</span></a><div class="project-body"><span class="project-category">${esc(x.category)}</span><h3><a href="projects/${x.slug}.html">${projectNames[i]} <span aria-hidden="true">↗</span></a></h3><p>${esc(x.summary)}</p>${chips(x.tags)}<a class="text-link" href="projects/${x.slug}.html" aria-label="Read case study: ${esc(x.fullTitle)}">Read case study ${icons.arrow}</a></div></article>`}).join('')}</div></section>
<section id="skills" class="section" data-story-label="The toolkit"><span class="chapter-kicker">04 / THE TOOLKIT</span><div class="section-title"><h2>Skills &amp; tools</h2><span class="margin-note">Collected along the way.</span></div><p class="section-intro">The tools changed as the responsibilities grew. Select one to see how it connects to my work.</p><div class="skill-pills" role="group" aria-label="Explore technology experience">${tools.map(([name,key,level,text,project],i)=>`<button type="button" class="skill-pill" disabled data-skill="${key}" data-level="${esc(level)}" data-description="${esc(text)}" data-project="${project}" data-evidence-label="${i>8?'Explore related work':'See it in practice'}" aria-pressed="${i===0}" aria-controls="skill-insight">${toolIcon(key)}<span>${esc(name)}</span></button>`).join('')}</div><div class="skill-insight" id="skill-insight"><div class="skill-insight-copy" aria-live="polite" aria-atomic="true"><span class="skill-insight-title">Python <span>Working experience</span></span><p>${tools[0][3]}</p></div><a class="skill-evidence" href="projects/data-automation.html">See it in practice ${icons.arrow}</a></div><noscript><p class="interaction-hint">Python, FastAPI, Docker, Git and Power BI: working experience. PostgreSQL, Linux, Microsoft 365 and Nginx: hands-on experience. Explore the case studies below for context.</p></noscript><div class="beyond-tools"><span>Beyond the tools</span><p>IT operations · Networking · MIS · User training · Technical documentation · Vendor coordination</p></div></section>
<section id="research" class="section" data-story-label="Shared knowledge"><span class="chapter-kicker">05 / SHARED KNOWLEDGE</span><div class="section-title"><h2>Research &amp; contributions</h2><span class="margin-note">From practice to shared knowledge.</span></div><p class="section-intro">Working with surveillance systems also brought me into collaborative research. These contributions connect the operational side of early warning with questions about forecasts, alerts and public-health action.</p><div class="research-list">${research.map((r,i)=>`<article class="research-row"><span class="research-icon">${icons.book}</span><div><div class="research-meta"><span>${r.year}</span>${i===0?'<span class="new-label">Latest contribution</span>':''}</div><h3>${esc(r.title)}</h3><p class="research-status">${esc(r.status)}</p><details class="research-details"><summary>Conference &amp; authors <span aria-hidden="true">+</span></summary><div><p>${esc(r.authors)}</p><p>${esc(r.venue)}</p>${r.note?`<p class="research-note">${esc(r.note)}</p>`:''}</div></details></div></article>`).join('')}</div></section>
${renderNext({icons})}
<section id="contact" class="section contact-section"><span class="small-label">LET’S START A CONVERSATION</span><h2>Let’s write the<br><em>next chapter.</em></h2><p>Looking for someone who understands both the systems and the people using them? I’m open to roles, consulting and collaborations in Bangladesh and internationally.</p><a class="button primary" href="mailto:${p.email}" data-contact-open>${icons.mail} Get in touch ${icons.arrow}</a><a class="contact-address" href="mailto:${p.email}" data-contact-open>${p.email}</a><div class="contact-footnote"><span>${icons.location} Based in Bangladesh</span><span>Roles · Consulting · Collaboration</span></div></section>
</main><nav class="story-index" aria-label="Story chapters"><span>THE STORY</span><a href="#about"><span>01</span>The beginning</a><a href="#experience"><span>02</span>The journey</a><a href="#projects"><span>03</span>The work</a><a href="#skills"><span>04</span>The toolkit</a><a href="#research"><span>05</span>Shared knowledge</a><a href="#next"><span>06</span>What’s next</a></nav>${dialog}${footer()}<nav class="floating-dock" aria-label="Quick navigation"><a href="#home" aria-label="Introduction" data-tip="Home">${icons.home}</a><a href="#experience" aria-label="Experience" data-tip="Experience">${icons.work}</a><a href="#projects" aria-label="Selected work" data-tip="Work">${icons.layers}</a><span class="dock-divider"></span><a href="${p.linkedin}" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn profile" data-tip="LinkedIn">${icons.linkedin}</a><a href="mailto:${p.email}" data-contact-open aria-label="Start a conversation" data-tip="Say hello">${icons.mail}</a><a href="assets/Sanjoy_Sarkar_CV.pdf" download aria-label="Download curriculum vitae" data-tip="CV">${icons.download}</a></nav></body></html>`;
}
