import { chapters } from '../data/journey.mjs';
import { experience } from '../data/portfolio.mjs';
const orgAssets=['iedcr-logo.png','winrock-logo.png','oxfam-logo.png','save-the-children-logo.svg'];
export function renderJourney({icons,esc}) {
 return `<section id="experience" class="section journey-section" data-story-label="The journey"><div class="chapter-heading"><span class="chapter-kicker">02 / THE JOURNEY</span><div class="section-title"><h2>Four chapters.<br><em>A wider perspective.</em></h2><span class="margin-note">2018 → 2026</span></div><p>Each role added something new. Follow the chapters to see how my work grew from enterprise support to digital-health systems.</p></div><div class="journey-tabs" aria-label="Career chapters">${chapters.map((c,i)=>`<a id="chapter-tab-${c.id}" href="#chapter-${c.id}" data-chapter="${c.id}"><span class="chapter-dot" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><span class="chapter-year">${c.year}</span><span class="chapter-tab-label">${c.label}</span></a>`).join('')}</div><div class="journey-panels">${chapters.map((c,i)=>{const x=experience[c.roleIndex];return `<article class="journey-panel theme-${c.theme}" id="chapter-${c.id}" aria-labelledby="chapter-title-${c.id}"><div class="journey-panel-top"><div class="chapter-org"><span class="org-icon"><img src="assets/${orgAssets[c.roleIndex]}" alt="" width="42" height="42" loading="lazy"></span><div><strong>${esc(c.org)}</strong><span>${esc(x.role)}</span></div></div><span class="chapter-period">${esc(x.dates)}</span></div><div class="journey-panel-grid"><div class="chapter-narrative"><h3 id="chapter-title-${c.id}">${esc(c.title)}</h3><p>${esc(c.summary)}</p><p>${esc(c.transition)}</p><a class="text-link" href="projects/${c.project}.html">${esc(c.projectLabel)} ${icons.arrow}</a></div><aside class="chapter-notebook" aria-label="Chapter ${i+1} at a glance"><div class="notebook-top"><span>FIELD NOTES / ${String(i+1).padStart(2,'0')}</span>${icons[c.icon]}</div><p class="notebook-context">${esc(c.context)}</p><ol>${c.focus.map(f=>`<li>${esc(f)}</li>`).join('')}</ol><div class="chapter-lesson"><span>What this chapter reinforced</span><p>${esc(c.takeaway)}</p></div></aside></div><details class="chapter-responsibilities"><summary>Go deeper: responsibilities &amp; tools <span aria-hidden="true">+</span></summary><ul>${x.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul><div class="tags">${x.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div></details><p class="chapter-transition"><span aria-hidden="true">↳</span> ${esc(c.next)}</p></article>`}).join('')}</div><div class="journey-controls" hidden><button type="button" data-chapter-step="-1" aria-label="Previous career chapter">← Previous</button><span class="journey-position" aria-live="polite">Chapter 1 of 4</span><button type="button" data-chapter-step="1" aria-label="Next career chapter">Next chapter →</button><a class="journey-finish" href="#next" hidden>Where I’m headed ${icons.arrow}</a></div></section>`;
}
export function renderOrigin({icons}) {
 return `<section id="about" class="section origin-section" data-story-label="The beginning"><span class="chapter-kicker">01 / THE BEGINNING</span><div class="origin-grid"><div><h2>A foundation in code.<br><em>An education in people.</em></h2><p>I studied Computer Science and Engineering at Jawaharlal Nehru Technological University in India, from 2014 to 2018. In October 2018, I began my professional journey in ICT infrastructure at Save the Children Bangladesh.</p><p>The common thread since then? <strong>Understanding the people behind a technical problem</strong>—and making the systems they use more dependable.</p></div><aside class="origin-card"><span class="origin-stamp">THE STARTING POINT</span>${icons.school}<strong>2014—2018</strong><span>B.Sc. in Computer Science<br>&amp; Engineering</span><div class="origin-route"><span>India</span><i aria-hidden="true">→</i><span>Bangladesh</span></div><small>From university to enterprise ICT.</small></aside></div><a class="story-cue" href="#experience">And then, the real-world learning began. ${icons.arrow}</a></section>`;
}
export function renderNext({icons}) {
 return `<section id="next" class="section next-section" data-story-label="The next chapter"><span class="chapter-kicker">06 / THE NEXT CHAPTER</span><div class="section-title"><h2>Experience to build on.<br><em>More to discover.</em></h2><span class="margin-note">The story is still being written.</span></div><div class="now-next-grid"><article class="now-card"><span class="small-label">WHERE I AM NOW</span><h3>Bringing the pieces together.</h3><p>My most recent role at IEDCR brought infrastructure, application operations and data workflows into the same picture. I’m now looking to bring that combined experience to a new team.</p><div class="current-study" id="education">${icons.school}<div><span>Currently studying</span><h4>Professional Master’s in AI &amp; Data Engineering</h4><p>University of Dhaka · Ongoing</p></div></div><p class="study-note">Developing deeper foundations in AI, machine learning, statistics and data engineering.</p></article><article class="next-card"><span class="small-label">WHAT I’M LOOKING FORWARD TO</span><h3>A broader contribution.<br>A new team to learn with.</h3><p>I’m interested in roles where I can combine dependable IT operations with better digital systems—and continue growing technically.</p><ul class="opportunity-list"><li>${icons.layers}<span>IT operations &amp; infrastructure</span></li><li>${icons.database}<span>Digital systems, MIS &amp; data</span></li><li>${icons.globe}<span>Digital health &amp; development</span></li></ul><a href="mailto:imsanjoy562@gmail.com" class="text-link" data-contact-open>Have a role in mind? Let’s talk ${icons.arrow}</a></article></div></section>`;
}
